// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ServerMetaData.proto

#ifndef PROTOBUF_ServerMetaData_2eproto__INCLUDED
#define PROTOBUF_ServerMetaData_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_ServerMetaData_2eproto();
void protobuf_AssignDesc_ServerMetaData_2eproto();
void protobuf_ShutdownFile_ServerMetaData_2eproto();

class ServerMetaData;
class ServerMetaData_Sensor;

// ===================================================================

class ServerMetaData_Sensor : public ::google::protobuf::Message {
 public:
  ServerMetaData_Sensor();
  virtual ~ServerMetaData_Sensor();

  ServerMetaData_Sensor(const ServerMetaData_Sensor& from);

  inline ServerMetaData_Sensor& operator=(const ServerMetaData_Sensor& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerMetaData_Sensor& default_instance();

  void Swap(ServerMetaData_Sensor* other);

  // implements Message ----------------------------------------------

  ServerMetaData_Sensor* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerMetaData_Sensor& from);
  void MergeFrom(const ServerMetaData_Sensor& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 sensorId = 1;
  inline bool has_sensorid() const;
  inline void clear_sensorid();
  static const int kSensorIdFieldNumber = 1;
  inline ::google::protobuf::uint32 sensorid() const;
  inline void set_sensorid(::google::protobuf::uint32 value);

  // optional string sensorName = 2;
  inline bool has_sensorname() const;
  inline void clear_sensorname();
  static const int kSensorNameFieldNumber = 2;
  inline const ::std::string& sensorname() const;
  inline void set_sensorname(const ::std::string& value);
  inline void set_sensorname(const char* value);
  inline void set_sensorname(const char* value, size_t size);
  inline ::std::string* mutable_sensorname();
  inline ::std::string* release_sensorname();
  inline void set_allocated_sensorname(::std::string* sensorname);

  // @@protoc_insertion_point(class_scope:ServerMetaData.Sensor)
 private:
  inline void set_has_sensorid();
  inline void clear_has_sensorid();
  inline void set_has_sensorname();
  inline void clear_has_sensorname();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::std::string* sensorname_;
  ::google::protobuf::uint32 sensorid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_ServerMetaData_2eproto();
  friend void protobuf_AssignDesc_ServerMetaData_2eproto();
  friend void protobuf_ShutdownFile_ServerMetaData_2eproto();

  void InitAsDefaultInstance();
  static ServerMetaData_Sensor* default_instance_;
};
// -------------------------------------------------------------------

class ServerMetaData : public ::google::protobuf::Message {
 public:
  ServerMetaData();
  virtual ~ServerMetaData();

  ServerMetaData(const ServerMetaData& from);

  inline ServerMetaData& operator=(const ServerMetaData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ServerMetaData& default_instance();

  void Swap(ServerMetaData* other);

  // implements Message ----------------------------------------------

  ServerMetaData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ServerMetaData& from);
  void MergeFrom(const ServerMetaData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef ServerMetaData_Sensor Sensor;

  // accessors -------------------------------------------------------

  // repeated .ServerMetaData.Sensor sensors = 1;
  inline int sensors_size() const;
  inline void clear_sensors();
  static const int kSensorsFieldNumber = 1;
  inline const ::ServerMetaData_Sensor& sensors(int index) const;
  inline ::ServerMetaData_Sensor* mutable_sensors(int index);
  inline ::ServerMetaData_Sensor* add_sensors();
  inline const ::google::protobuf::RepeatedPtrField< ::ServerMetaData_Sensor >&
      sensors() const;
  inline ::google::protobuf::RepeatedPtrField< ::ServerMetaData_Sensor >*
      mutable_sensors();

  // @@protoc_insertion_point(class_scope:ServerMetaData)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::ServerMetaData_Sensor > sensors_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_ServerMetaData_2eproto();
  friend void protobuf_AssignDesc_ServerMetaData_2eproto();
  friend void protobuf_ShutdownFile_ServerMetaData_2eproto();

  void InitAsDefaultInstance();
  static ServerMetaData* default_instance_;
};
// ===================================================================


// ===================================================================

// ServerMetaData_Sensor

// required uint32 sensorId = 1;
inline bool ServerMetaData_Sensor::has_sensorid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ServerMetaData_Sensor::set_has_sensorid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ServerMetaData_Sensor::clear_has_sensorid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ServerMetaData_Sensor::clear_sensorid() {
  sensorid_ = 0u;
  clear_has_sensorid();
}
inline ::google::protobuf::uint32 ServerMetaData_Sensor::sensorid() const {
  return sensorid_;
}
inline void ServerMetaData_Sensor::set_sensorid(::google::protobuf::uint32 value) {
  set_has_sensorid();
  sensorid_ = value;
}

// optional string sensorName = 2;
inline bool ServerMetaData_Sensor::has_sensorname() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ServerMetaData_Sensor::set_has_sensorname() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ServerMetaData_Sensor::clear_has_sensorname() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ServerMetaData_Sensor::clear_sensorname() {
  if (sensorname_ != &::google::protobuf::internal::kEmptyString) {
    sensorname_->clear();
  }
  clear_has_sensorname();
}
inline const ::std::string& ServerMetaData_Sensor::sensorname() const {
  return *sensorname_;
}
inline void ServerMetaData_Sensor::set_sensorname(const ::std::string& value) {
  set_has_sensorname();
  if (sensorname_ == &::google::protobuf::internal::kEmptyString) {
    sensorname_ = new ::std::string;
  }
  sensorname_->assign(value);
}
inline void ServerMetaData_Sensor::set_sensorname(const char* value) {
  set_has_sensorname();
  if (sensorname_ == &::google::protobuf::internal::kEmptyString) {
    sensorname_ = new ::std::string;
  }
  sensorname_->assign(value);
}
inline void ServerMetaData_Sensor::set_sensorname(const char* value, size_t size) {
  set_has_sensorname();
  if (sensorname_ == &::google::protobuf::internal::kEmptyString) {
    sensorname_ = new ::std::string;
  }
  sensorname_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ServerMetaData_Sensor::mutable_sensorname() {
  set_has_sensorname();
  if (sensorname_ == &::google::protobuf::internal::kEmptyString) {
    sensorname_ = new ::std::string;
  }
  return sensorname_;
}
inline ::std::string* ServerMetaData_Sensor::release_sensorname() {
  clear_has_sensorname();
  if (sensorname_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = sensorname_;
    sensorname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ServerMetaData_Sensor::set_allocated_sensorname(::std::string* sensorname) {
  if (sensorname_ != &::google::protobuf::internal::kEmptyString) {
    delete sensorname_;
  }
  if (sensorname) {
    set_has_sensorname();
    sensorname_ = sensorname;
  } else {
    clear_has_sensorname();
    sensorname_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// ServerMetaData

// repeated .ServerMetaData.Sensor sensors = 1;
inline int ServerMetaData::sensors_size() const {
  return sensors_.size();
}
inline void ServerMetaData::clear_sensors() {
  sensors_.Clear();
}
inline const ::ServerMetaData_Sensor& ServerMetaData::sensors(int index) const {
  return sensors_.Get(index);
}
inline ::ServerMetaData_Sensor* ServerMetaData::mutable_sensors(int index) {
  return sensors_.Mutable(index);
}
inline ::ServerMetaData_Sensor* ServerMetaData::add_sensors() {
  return sensors_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::ServerMetaData_Sensor >&
ServerMetaData::sensors() const {
  return sensors_;
}
inline ::google::protobuf::RepeatedPtrField< ::ServerMetaData_Sensor >*
ServerMetaData::mutable_sensors() {
  return &sensors_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_ServerMetaData_2eproto__INCLUDED
