// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TemperatureData.proto

#ifndef PROTOBUF_TemperatureData_2eproto__INCLUDED
#define PROTOBUF_TemperatureData_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_TemperatureData_2eproto();
void protobuf_AssignDesc_TemperatureData_2eproto();
void protobuf_ShutdownFile_TemperatureData_2eproto();

class TemperatureData;
class TemperatureData_Temperature;

// ===================================================================

class TemperatureData_Temperature : public ::google::protobuf::Message {
 public:
  TemperatureData_Temperature();
  virtual ~TemperatureData_Temperature();

  TemperatureData_Temperature(const TemperatureData_Temperature& from);

  inline TemperatureData_Temperature& operator=(const TemperatureData_Temperature& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TemperatureData_Temperature& default_instance();

  void Swap(TemperatureData_Temperature* other);

  // implements Message ----------------------------------------------

  TemperatureData_Temperature* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TemperatureData_Temperature& from);
  void MergeFrom(const TemperatureData_Temperature& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required uint32 timestamp = 1;
  inline bool has_timestamp() const;
  inline void clear_timestamp();
  static const int kTimestampFieldNumber = 1;
  inline ::google::protobuf::uint32 timestamp() const;
  inline void set_timestamp(::google::protobuf::uint32 value);

  // required uint32 temperature = 2;
  inline bool has_temperature() const;
  inline void clear_temperature();
  static const int kTemperatureFieldNumber = 2;
  inline ::google::protobuf::uint32 temperature() const;
  inline void set_temperature(::google::protobuf::uint32 value);

  // required uint32 humidity = 3;
  inline bool has_humidity() const;
  inline void clear_humidity();
  static const int kHumidityFieldNumber = 3;
  inline ::google::protobuf::uint32 humidity() const;
  inline void set_humidity(::google::protobuf::uint32 value);

  // required uint32 uniqueId = 4;
  inline bool has_uniqueid() const;
  inline void clear_uniqueid();
  static const int kUniqueIdFieldNumber = 4;
  inline ::google::protobuf::uint32 uniqueid() const;
  inline void set_uniqueid(::google::protobuf::uint32 value);

  // @@protoc_insertion_point(class_scope:TemperatureData.Temperature)
 private:
  inline void set_has_timestamp();
  inline void clear_has_timestamp();
  inline void set_has_temperature();
  inline void clear_has_temperature();
  inline void set_has_humidity();
  inline void clear_has_humidity();
  inline void set_has_uniqueid();
  inline void clear_has_uniqueid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 timestamp_;
  ::google::protobuf::uint32 temperature_;
  ::google::protobuf::uint32 humidity_;
  ::google::protobuf::uint32 uniqueid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_TemperatureData_2eproto();
  friend void protobuf_AssignDesc_TemperatureData_2eproto();
  friend void protobuf_ShutdownFile_TemperatureData_2eproto();

  void InitAsDefaultInstance();
  static TemperatureData_Temperature* default_instance_;
};
// -------------------------------------------------------------------

class TemperatureData : public ::google::protobuf::Message {
 public:
  TemperatureData();
  virtual ~TemperatureData();

  TemperatureData(const TemperatureData& from);

  inline TemperatureData& operator=(const TemperatureData& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TemperatureData& default_instance();

  void Swap(TemperatureData* other);

  // implements Message ----------------------------------------------

  TemperatureData* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TemperatureData& from);
  void MergeFrom(const TemperatureData& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  typedef TemperatureData_Temperature Temperature;

  // accessors -------------------------------------------------------

  // required uint32 sensorId = 1;
  inline bool has_sensorid() const;
  inline void clear_sensorid();
  static const int kSensorIdFieldNumber = 1;
  inline ::google::protobuf::uint32 sensorid() const;
  inline void set_sensorid(::google::protobuf::uint32 value);

  // repeated .TemperatureData.Temperature temperatures = 2;
  inline int temperatures_size() const;
  inline void clear_temperatures();
  static const int kTemperaturesFieldNumber = 2;
  inline const ::TemperatureData_Temperature& temperatures(int index) const;
  inline ::TemperatureData_Temperature* mutable_temperatures(int index);
  inline ::TemperatureData_Temperature* add_temperatures();
  inline const ::google::protobuf::RepeatedPtrField< ::TemperatureData_Temperature >&
      temperatures() const;
  inline ::google::protobuf::RepeatedPtrField< ::TemperatureData_Temperature >*
      mutable_temperatures();

  // @@protoc_insertion_point(class_scope:TemperatureData)
 private:
  inline void set_has_sensorid();
  inline void clear_has_sensorid();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedPtrField< ::TemperatureData_Temperature > temperatures_;
  ::google::protobuf::uint32 sensorid_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];

  friend void  protobuf_AddDesc_TemperatureData_2eproto();
  friend void protobuf_AssignDesc_TemperatureData_2eproto();
  friend void protobuf_ShutdownFile_TemperatureData_2eproto();

  void InitAsDefaultInstance();
  static TemperatureData* default_instance_;
};
// ===================================================================


// ===================================================================

// TemperatureData_Temperature

// required uint32 timestamp = 1;
inline bool TemperatureData_Temperature::has_timestamp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TemperatureData_Temperature::set_has_timestamp() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TemperatureData_Temperature::clear_has_timestamp() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TemperatureData_Temperature::clear_timestamp() {
  timestamp_ = 0u;
  clear_has_timestamp();
}
inline ::google::protobuf::uint32 TemperatureData_Temperature::timestamp() const {
  return timestamp_;
}
inline void TemperatureData_Temperature::set_timestamp(::google::protobuf::uint32 value) {
  set_has_timestamp();
  timestamp_ = value;
}

// required uint32 temperature = 2;
inline bool TemperatureData_Temperature::has_temperature() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void TemperatureData_Temperature::set_has_temperature() {
  _has_bits_[0] |= 0x00000002u;
}
inline void TemperatureData_Temperature::clear_has_temperature() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void TemperatureData_Temperature::clear_temperature() {
  temperature_ = 0u;
  clear_has_temperature();
}
inline ::google::protobuf::uint32 TemperatureData_Temperature::temperature() const {
  return temperature_;
}
inline void TemperatureData_Temperature::set_temperature(::google::protobuf::uint32 value) {
  set_has_temperature();
  temperature_ = value;
}

// required uint32 humidity = 3;
inline bool TemperatureData_Temperature::has_humidity() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void TemperatureData_Temperature::set_has_humidity() {
  _has_bits_[0] |= 0x00000004u;
}
inline void TemperatureData_Temperature::clear_has_humidity() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void TemperatureData_Temperature::clear_humidity() {
  humidity_ = 0u;
  clear_has_humidity();
}
inline ::google::protobuf::uint32 TemperatureData_Temperature::humidity() const {
  return humidity_;
}
inline void TemperatureData_Temperature::set_humidity(::google::protobuf::uint32 value) {
  set_has_humidity();
  humidity_ = value;
}

// required uint32 uniqueId = 4;
inline bool TemperatureData_Temperature::has_uniqueid() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void TemperatureData_Temperature::set_has_uniqueid() {
  _has_bits_[0] |= 0x00000008u;
}
inline void TemperatureData_Temperature::clear_has_uniqueid() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void TemperatureData_Temperature::clear_uniqueid() {
  uniqueid_ = 0u;
  clear_has_uniqueid();
}
inline ::google::protobuf::uint32 TemperatureData_Temperature::uniqueid() const {
  return uniqueid_;
}
inline void TemperatureData_Temperature::set_uniqueid(::google::protobuf::uint32 value) {
  set_has_uniqueid();
  uniqueid_ = value;
}

// -------------------------------------------------------------------

// TemperatureData

// required uint32 sensorId = 1;
inline bool TemperatureData::has_sensorid() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void TemperatureData::set_has_sensorid() {
  _has_bits_[0] |= 0x00000001u;
}
inline void TemperatureData::clear_has_sensorid() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void TemperatureData::clear_sensorid() {
  sensorid_ = 0u;
  clear_has_sensorid();
}
inline ::google::protobuf::uint32 TemperatureData::sensorid() const {
  return sensorid_;
}
inline void TemperatureData::set_sensorid(::google::protobuf::uint32 value) {
  set_has_sensorid();
  sensorid_ = value;
}

// repeated .TemperatureData.Temperature temperatures = 2;
inline int TemperatureData::temperatures_size() const {
  return temperatures_.size();
}
inline void TemperatureData::clear_temperatures() {
  temperatures_.Clear();
}
inline const ::TemperatureData_Temperature& TemperatureData::temperatures(int index) const {
  return temperatures_.Get(index);
}
inline ::TemperatureData_Temperature* TemperatureData::mutable_temperatures(int index) {
  return temperatures_.Mutable(index);
}
inline ::TemperatureData_Temperature* TemperatureData::add_temperatures() {
  return temperatures_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::TemperatureData_Temperature >&
TemperatureData::temperatures() const {
  return temperatures_;
}
inline ::google::protobuf::RepeatedPtrField< ::TemperatureData_Temperature >*
TemperatureData::mutable_temperatures() {
  return &temperatures_;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_TemperatureData_2eproto__INCLUDED
